### ISSUE TITLE
move sphinx down a level in directory hierarchy

### ISSUE THREAD

**Issue by diekhans** [Jeltje/ga4gh-schemas#22]
to keep the top level more generic, create a tools directory and move sphinx to sphinx/tools.

Please make changes in documentation branch.

**Comment by hjellinek** [comment]
I think you mean that I should move it to `tools/sphinx`.

**Comment by diekhans** [comment]
Yes. ..

-- Sent from my computer phone

-----Original Message-----

**Comment by hjellinek** [comment]
Good, just wanted to make sure.
