### ISSUE TITLE
put make in charge

### ISSUE THREAD

**Issue by diekhans** [Jeltje/ga4gh-schemas#26]
implement documentation build using make command rather than a script that runs make.
Or move it to mvn

**Comment by hjellinek** [comment]
The Makefile that's in there is a standard part of Sphinx.  If I tinker with it or replace it, I'm afraid we'll lose compatibility with Sphinx - in effect, we'll have our own Sphinx to maintain.

I can replace the generate_sphinx_docs.sh script with Maven, but the result will be a pom.xml containing a bunch of shell commands shoved into Maven's XML syntax.  I don't think that will be an improvement!

I like the approach you suggest in #27 much better.

**Comment by diekhans** [comment]
Herb Jellinek notifications@github.com writes:

> I can replace the generate_sphinx_docs.sh script with Maven, but the result
> will be a pom.xml containing a bunch of shell commands shoved into Maven's XML
> syntax. I don't think that will be an improvement!

I meant run generate_sphinx_docs.sh, not put it XML, which you are 
right, putting anything in XML is not an improvement.

> I like the approach you suggest in #27 much better.

Yes!!

**Comment by hjellinek** [comment]
> I meant run generate_sphinx_docs.sh, not put it XML, which you are right, putting anything in XML is not an improvement.

OK, I'm glad that's what you meant.  The single line that invokes generate_sphinx_docs.sh will, unavoidably, be plopped in the middle of a bunch of XML, but that's the nature of a pom.xml file.

**Comment by hjellinek** [comment]
I moved it to Maven.
