### ISSUE TITLE
Link up the whole doc build

### ISSUE THREAD

**Issue by diekhans** [Jeltje/ga4gh-schemas#27]
Ideal situation:

At the top level, once dependencies are installed:
    mvn  doc
od
    make doc

This generates a directory containing sphinx from the manual documentation and the avro schemas in a form that can be copied the the website or uploaded to readthedocs.org.  A clean target reset everything.

**Comment by hjellinek** [comment]
The top-level POM should fetch avro-tools.jar.

**Comment by hjellinek** [comment]
Done using Maven (`mvn package`).
