### ISSUE TITLE
clean up source files

### ISSUE THREAD

**Issue by diekhans** [Jeltje/ga4gh-schemas#28]
- what is sphinx/build.py.  It is undocumented and appears unused.  Delete if true.
- what happened to Adam's graphviz UML builder that was in contrib.  It would be good to keep that in the doc.
- mvn should handle managing avrotools jar get

**Comment by hjellinek** [comment]
1. The build.py file looks like a quick test the original developer did.  Clearly not necessary.
2. The UML builder depended on Doxygen, if I understood the code correctly, and I was given to understand that we wanted to replace Doxygen with Sphinx.  There are offline UML tools we can use for generating reference docs, if that's what you're interested in.  IIRC, the UML builder docs stated that they were not completely automated: they still required that you lay out the diagrams by hand.
3. Agreed.  This could be part of #27.

**Comment by diekhans** [comment]
The auto-generate UML was fairly ugly single it used a automatic
general graph layout package

See
        https://github.com/ga4gh/schemas/issues/402

but what Heng did in converting to SQL seems hard to maintain.
